
name: Deploy
on:
  push:
    branches: [main]

jobs:
  build-upload:
    runs-on: macos-latest
    steps:
    - name: iOS app
      run: xcodebuild -scheme "cicd-setup" clean archive -archivePath "Actions" -configuration "Release Production"
    - name: export ipa
      env: 
        EXPORT_PLIST: ${{ secrets.IOS_EXPORT_PRODUCTION }}
      run: |
        # crete export options
        EXPORT_PLIST_PATH=$RUNNER_TEMP/ExportOptions.plist
        echo -n "$EXPORT_PLIST" | base64 --decode --output $EXPORT_PLIST_PATH
        xcodebuild -exportArchive -archivePath $GITHUB_WORKSPACE/Actions.xcarchive -exportOptionsPlist $EXPORT_PLIST_PATH -exportPath $RUNNER_TEMP/export
    - name: Rename the file, remove whitespace
      run: |
        echo Export directory contents:
        ls /Users/cobemacmini/ios-runner/_work/_temp/export/
        mv "/Users/cobemacmini/ios-runner/_work/_temp/export/Actions Production.ipa" "/Users/cobemacmini/ios-runner/_work/_temp/export/ActionsProduction.ipa"
        ls /Users/cobemacmini/ios-runner/_work/_temp/export/
    - name: Decode auth. api key file and save it
      env:
        API_KEY_BASE64: $({ secrets.APPSTORE_API_PRIVATE_KEY }}
      run: |
        ls ~/private keys
        echo -n "$API_KEY_BASE64" | base64 --decode --output ~/private_keys/Authkey_${{ secrets.APPSTORE_API_KEY_ID }}.p8
        echo "After saving: "
        ls ~/private keys
    - name: "Upload file to test flight using CLI"
      run: |
        echo "Starting upload."
        ls ~/private keys
        ×crun altool --validate-app -f /Users/cobemacmini/ios-runner/_work/_temp/export/ActionsProduction.ipa -t ios --apikey ${{ secrets.APPSTORE_API_KEY_ID }}
        ×crun altool --upload-app -f /Users/cobemacmini/ios-runner/_work/_temp/export/ActionsProduction.ipa -t ios --apikey ${{ secrets.APPSTORE_API_KEY_ID }}